[project]
name = "flyrank-capstone-image-relevance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SubanaSharma", email = "subonasharma314@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "sqlmodel>=0.0.42",
]

[project.scripts]
flyrank-capstone-image-relevance = "flyrank_capstone_image_relevance:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
